export * from './NavBar'
export * from './Hero'
export * from './Testimonials'
export * from './Instructors'
export * from './Courses'
export * from './FAQ'
export * from './CTA'
export * from './Footer'